#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
#
#

# Ensure that a non-login, non-interactive shell has a defined environment.
export ZDOTDIR=~/.config/zsh

if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

#
# Language
#
if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

export PATH="/home/sam/sd:$PATH"
export PATH="/home/sam/.local/bin:$PATH"
export PATH


# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
  $PATH
)

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path


# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Editors
#
export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='batcat'
export XDG_CURRENT_DESKTOP=Unity
