fpath=(~/dotfiles/zsh/.config/zsh/sd $fpath)
fpath=(~/dotfiles/zsh/.config/zsh/completions $fpath)
autoload -Uz compinit
compinit

export HISTFILE=~/.local/share/zsh/zsh_history
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
export HISTSIZE=10000
export SAVEHIST=10000

export SD_CAT="batcat"
export MANPAGER='nvim +Man!'

### MAKE VIM MODE TOLERABLE

# Cursor changes depending on vi-mode
zle-keymap-select () {
if [ $KEYMAP = vicmd ]; then
    printf "\033[2 q"
else
    printf "\033[6 q"
fi
}
zle -N zle-keymap-select
zle-line-init () {
zle -K viins
printf "\033[6 q"
}
zle -N zle-line-init

# Fix weird backspace key behaviour in vi mode
vi-search-fix() {
zle vi-cmd-mode
zle .vi-history-search-backward
}
autoload vi-search-fix
zle -N vi-search-fix
bindkey -M viins '\e/' vi-search-fix
bindkey "^?" backward-delete-char
bindkey "^W" backward-kill-word 
bindkey "^U" backward-kill-line

# Make esc in vi-mode actually responsive
KEYTIMEOUT=1
bindkey -M vicmd '^[' undefined-key
bindkey -rM viins '^X'
bindkey -M viins '^X,' _history-complete-newer \
                 '^X/' _history-complete-older \
                 '^X`' _bash_complete-word

bindkey -v
####


# Enable completion in sudo
zstyle ':completion::complete:*' gain-privileges 1

# aliases
alias ls='exa -l'
alias grep='rg'
alias cat="batcat"
alias bat="batcat"
alias vim="nvim"
alias vi="nvim"
alias lynx="lynx -cookies-"
alias lg="lazygit"
alias td="topydo"
alias b="buku --suggest"
alias ta="topydo add"
alias fd="fdfind"
alias rmdir='rmdirtrash'
alias qn='sd tmux qn'
# alias hist='fzf `history 0`'
alias fa='fzf --preview "batcat --color=always {}"'
alias sess='tmux new -s'
alias upgrade='sd sys upgrade'
alias w3m='w3m -sixel -o auto_image=TRUE -o display_image=1 -T text/html'
alias nvminit='source ~/.config/zsh/loadnvm'

source ~/.local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ZDOTDIR/spaceship-prompt/spaceship.zsh



eval "$(zoxide init zsh)"

### FZF STUFF
source /usr/share/fzf/shell/key-bindings.zsh
export FZF_DEFAULT_COMMAND="fdfind . $HOME"
#
# restore fzf default options ('fzf clear')
alias fzfcl="export FZF_DEFAULT_COMMAND='fd .'"

# reinstate fzf custom options ('fzf-' as in 'cd -' as in 'back to where I was')
alias fzf-="export FZF_DEFAULT_COMMAND='fd . $HOME'"

source /usr/share/fzf/shell/completion.zsh
source ~/.fzf.zsh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


# fh - repeat history
function hist {
  print -z $( ([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf +s --tac | sed -E 's/ *[0-9]*\*? *//' | sed -E 's/\\/\\\\/g')
}



_fzf_compgen_path() {
  fd --hidden --follow --exclude ".git .obsidian" . "$1"
}

# Use fd to generate the list for directory completion
_fzf_compgen_dir() {
  fd --type d --hidden --follow --exclude ".git" . "$1"
}

# Yazi wrapper
function yy() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}

alias lnvm="source $HOME/.config/zsh/loadnvm"

## Go
export PATH=$PATH:/usr/local/go/bin

